#Server
server:
  servlet:
    context-path: /api

# Database
spring:
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/tms?useSSL=false
     username: postgres
     password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lesson27_jdbc
#    username: root
#    password: 9366
  jpa:
    hibernate:
#      ddl-auto: validate
      ddl-auto: create
      dialect-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  jackson:
    default-property-inclusion:
      - non_null
      - non_empty
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

# Logging
logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug

springdoc:
  swagger-ui:
    enabled: true

product:
  min:
    price: 100
